CREATE DATABASE jarvis ENCODING 'UTF8';

ALTER DATABASE jarvis SET timezone TO 'UTC';

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
