"""add_dynamic_roles_and_persona

Revision ID: 04468d73b4d2
Revises: b22002200220
Create Date: 2025-12-09 19:32:15.786459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04468d73b4d2'
down_revision: Union[str, Sequence[str], None] = 'b22002200220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('escalation_rules', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('escalation_rules', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('escalation_rules', 'trigger_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('TIE_VOTE', 'QUORUM_FAILED', 'CSI_BELOW_THRESHOLD', 'CONFLICT_THRESHOLD', 'CONSTITUTIONAL_CONFLICT', 'MANUAL', 'TIMEOUT', name='escalation_trigger'),
               comment=None,
               existing_comment='tie_vote | quorum_failure | csi_threshold | constitutional_conflict | timeout',
               existing_nullable=False)
    op.alter_column('escalation_rules', 'escalate_to_role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OWNER', 'ADMIN', 'CONTRIBUTOR', 'OBSERVER', name='escalate_role'),
               existing_nullable=False)
    op.alter_column('escalation_rules', 'timeout_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Hours before auto-escalation')
    op.alter_column('escalation_rules', 'auto_escalate_further',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('escalation_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('escalation_rules', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='Lower = higher priority',
               existing_nullable=False)
    op.alter_column('escalation_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_escalation_rules_is_active'), table_name='escalation_rules')
    op.drop_index(op.f('ix_escalation_rules_trigger_type'), table_name='escalation_rules')
    op.create_index('ix_escalation_rules_active', 'escalation_rules', ['is_active'], unique=False)
    op.create_index('ix_escalation_rules_trigger', 'escalation_rules', ['trigger_type'], unique=False)
    op.create_unique_constraint(None, 'escalation_rules', ['name'])
    op.drop_column('escalation_rules', 'updated_at')
    op.alter_column('escalations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('escalations', 'rule_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='Link to trigger rule')
    op.alter_column('escalations', 'trigger_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('TIE_VOTE', 'QUORUM_FAILED', 'CSI_BELOW_THRESHOLD', 'CONFLICT_THRESHOLD', 'CONSTITUTIONAL_CONFLICT', 'MANUAL', 'TIMEOUT', name='esc_trigger'),
               existing_nullable=False)
    op.alter_column('escalations', 'trigger_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               comment=None,
               existing_comment='Full context of what triggered escalation')
    op.alter_column('escalations', 'current_role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OWNER', 'ADMIN', 'CONTRIBUTOR', 'OBSERVER', name='current_esc_role'),
               comment=None,
               existing_comment='contributor | admin | owner',
               existing_nullable=False)
    op.alter_column('escalations', 'assigned_to',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Currently assigned user',
               existing_nullable=True)
    op.alter_column('escalations', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'EXPIRED', 'ESCALATED_FURTHER', name='escalation_status'),
               comment=None,
               existing_comment='pending | in_progress | resolved | expired',
               existing_nullable=False)
    op.alter_column('escalations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('escalations', 'escalation_chain',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='History of escalation path',
               existing_nullable=True)
    op.drop_index(op.f('ix_escalations_assigned_to'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_current_level'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_deadline_at'), table_name='escalations')
    op.create_index('ix_escalations_current_role', 'escalations', ['current_role'], unique=False)
    op.create_index('ix_escalations_deadline', 'escalations', ['deadline'], unique=False)
    op.create_index('ix_escalations_target', 'escalations', ['target_type', 'target_id'], unique=False)
    op.drop_constraint(op.f('escalations_rule_id_fkey'), 'escalations', type_='foreignkey')
    op.drop_constraint(op.f('escalations_resolved_by_fkey'), 'escalations', type_='foreignkey')
    op.drop_constraint(op.f('escalations_assigned_to_fkey'), 'escalations', type_='foreignkey')
    op.create_foreign_key(None, 'escalations', 'escalation_rules', ['rule_id'], ['id'])
    op.create_foreign_key(None, 'escalations', 'governance_users', ['resolved_by'], ['id'])
    op.create_foreign_key(None, 'escalations', 'governance_users', ['assigned_to'], ['id'])
    op.drop_column('escalations', 'updated_at')
    op.alter_column('governance_audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('governance_audit_log', 'action_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Action performed',
               existing_nullable=False)
    op.alter_column('governance_audit_log', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Type of resource affected',
               existing_nullable=False)
    op.alter_column('governance_audit_log', 'entity_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='ID of affected resource')
    op.alter_column('governance_audit_log', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Previous state',
               existing_nullable=True)
    op.alter_column('governance_audit_log', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='New state',
               existing_nullable=True)
    op.alter_column('governance_audit_log', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Additional context',
               existing_nullable=True)
    op.alter_column('governance_audit_log', 'actor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Actor (null for system actions)',
               existing_nullable=True)
    op.alter_column('governance_audit_log', 'actor_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('governance_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_governance_audit_log_action'), table_name='governance_audit_log')
    op.drop_index(op.f('ix_governance_audit_log_created_at'), table_name='governance_audit_log')
    op.drop_index(op.f('ix_governance_audit_log_resource_type'), table_name='governance_audit_log')
    op.drop_index(op.f('ix_governance_audit_log_user_id'), table_name='governance_audit_log')
    op.create_index('ix_audit_log_action', 'governance_audit_log', ['action_type'], unique=False)
    op.create_index('ix_audit_log_actor', 'governance_audit_log', ['actor_id'], unique=False)
    op.create_index('ix_audit_log_created', 'governance_audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'governance_audit_log', ['entity_type', 'entity_id'], unique=False)
    op.drop_constraint(op.f('governance_audit_log_user_id_fkey'), 'governance_audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'governance_audit_log', 'governance_users', ['actor_id'], ['id'])
    op.drop_column('governance_audit_log', 'user_agent')
    op.drop_column('governance_audit_log', 'ip_address')
    op.add_column('governance_users', sa.Column('platform_role', sa.Enum('ADMIN', 'USER', 'OBSERVER', name='platform_role'), nullable=False))
    op.add_column('governance_users', sa.Column('preferred_persona', sa.Enum('IRON_MAN', 'COPILOT', 'ADVISOR', name='user_persona'), nullable=False))
    op.alter_column('governance_users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('governance_users', 'issuer',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('governance_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OWNER', 'ADMIN', 'CONTRIBUTOR', 'OBSERVER', name='governance_role'),
               comment=None,
               existing_comment='owner | admin | contributor | observer',
               existing_nullable=False)
    op.alter_column('governance_users', 'trust_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('governance_users', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Explicit permission overrides',
               existing_nullable=True)
    op.alter_column('governance_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('governance_users', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('governance_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('governance_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_governance_users_is_active'), table_name='governance_users')
    op.drop_index(op.f('ix_governance_users_subject_id'), table_name='governance_users')
    op.create_index('ix_governance_users_subject_id', 'governance_users', ['subject_id', 'issuer'], unique=False)
    op.create_index('ix_governance_users_active', 'governance_users', ['is_active'], unique=False)
    op.create_index('ix_governance_users_platform_role', 'governance_users', ['platform_role'], unique=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('permissions', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('VIEW', 'VOTE', 'PROPOSE', 'AMEND', 'OVERRIDE', 'MANAGE_USERS', 'MODERATE', 'CONFIGURE', 'ALL', name='permission_action'),
               existing_nullable=False)
    op.alter_column('permissions', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OWNER', 'ADMIN', 'CONTRIBUTOR', 'OBSERVER', name='permission_role'),
               existing_nullable=False)
    op.alter_column('permissions', 'conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('permissions', 'conditions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('permissions', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'CONTRIBUTOR', 'OBSERVER', name='permission_role'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('permissions', 'action',
               existing_type=sa.Enum('VIEW', 'VOTE', 'PROPOSE', 'AMEND', 'OVERRIDE', 'MANAGE_USERS', 'MODERATE', 'CONFIGURE', 'ALL', name='permission_action'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index('ix_governance_users_platform_role', table_name='governance_users')
    op.drop_index('ix_governance_users_active', table_name='governance_users')
    op.drop_index('ix_governance_users_subject_id', table_name='governance_users')
    op.create_index(op.f('ix_governance_users_subject_id'), 'governance_users', ['subject_id', 'issuer'], unique=True)
    op.create_index(op.f('ix_governance_users_is_active'), 'governance_users', ['is_active'], unique=False)
    op.alter_column('governance_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('governance_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('governance_users', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('governance_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('governance_users', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Explicit permission overrides',
               existing_nullable=True)
    op.alter_column('governance_users', 'trust_scores',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('governance_users', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'CONTRIBUTOR', 'OBSERVER', name='governance_role'),
               type_=sa.VARCHAR(length=50),
               comment='owner | admin | contributor | observer',
               existing_nullable=False)
    op.alter_column('governance_users', 'issuer',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'https://jarvis.sovereign.idp'::character varying"),
               existing_nullable=False)
    op.alter_column('governance_users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('governance_users', 'preferred_persona')
    op.drop_column('governance_users', 'platform_role')
    op.add_column('governance_audit_log', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('governance_audit_log', sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'governance_audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('governance_audit_log_user_id_fkey'), 'governance_audit_log', 'governance_users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_audit_log_entity', table_name='governance_audit_log')
    op.drop_index('ix_audit_log_created', table_name='governance_audit_log')
    op.drop_index('ix_audit_log_actor', table_name='governance_audit_log')
    op.drop_index('ix_audit_log_action', table_name='governance_audit_log')
    op.create_index(op.f('ix_governance_audit_log_user_id'), 'governance_audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_log_resource_type'), 'governance_audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_governance_audit_log_created_at'), 'governance_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_governance_audit_log_action'), 'governance_audit_log', ['action_type'], unique=False)
    op.alter_column('governance_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('governance_audit_log', 'actor_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'user'::character varying"),
               nullable=True)
    op.alter_column('governance_audit_log', 'actor_id',
               existing_type=sa.UUID(),
               comment='Actor (null for system actions)',
               existing_nullable=True)
    op.alter_column('governance_audit_log', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional context',
               existing_nullable=True)
    op.alter_column('governance_audit_log', 'new_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='New state',
               existing_nullable=True)
    op.alter_column('governance_audit_log', 'old_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Previous state',
               existing_nullable=True)
    op.alter_column('governance_audit_log', 'entity_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='ID of affected resource')
    op.alter_column('governance_audit_log', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Type of resource affected',
               existing_nullable=False)
    op.alter_column('governance_audit_log', 'action_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Action performed',
               existing_nullable=False)
    op.alter_column('governance_audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('escalations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.create_foreign_key(op.f('escalations_assigned_to_fkey'), 'escalations', 'governance_users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('escalations_resolved_by_fkey'), 'escalations', 'governance_users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('escalations_rule_id_fkey'), 'escalations', 'escalation_rules', ['rule_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_escalations_target', table_name='escalations')
    op.drop_index('ix_escalations_deadline', table_name='escalations')
    op.drop_index('ix_escalations_current_role', table_name='escalations')
    op.create_index(op.f('ix_escalations_deadline_at'), 'escalations', ['deadline'], unique=False)
    op.create_index(op.f('ix_escalations_current_level'), 'escalations', ['current_role'], unique=False)
    op.create_index(op.f('ix_escalations_assigned_to'), 'escalations', ['assigned_to'], unique=False)
    op.alter_column('escalations', 'escalation_chain',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='History of escalation path',
               existing_nullable=True)
    op.alter_column('escalations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('escalations', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'EXPIRED', 'ESCALATED_FURTHER', name='escalation_status'),
               server_default=sa.text("'''pending'''::character varying"),
               type_=sa.VARCHAR(length=50),
               comment='pending | in_progress | resolved | expired',
               existing_nullable=False)
    op.alter_column('escalations', 'assigned_to',
               existing_type=sa.UUID(),
               comment='Currently assigned user',
               existing_nullable=True)
    op.alter_column('escalations', 'current_role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'CONTRIBUTOR', 'OBSERVER', name='current_esc_role'),
               type_=sa.VARCHAR(length=50),
               comment='contributor | admin | owner',
               existing_nullable=False)
    op.alter_column('escalations', 'trigger_context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment='Full context of what triggered escalation')
    op.alter_column('escalations', 'trigger_type',
               existing_type=sa.Enum('TIE_VOTE', 'QUORUM_FAILED', 'CSI_BELOW_THRESHOLD', 'CONFLICT_THRESHOLD', 'CONSTITUTIONAL_CONFLICT', 'MANUAL', 'TIMEOUT', name='esc_trigger'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('escalations', 'rule_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Link to trigger rule')
    op.alter_column('escalations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('escalation_rules', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'escalation_rules', type_='unique')
    op.drop_index('ix_escalation_rules_trigger', table_name='escalation_rules')
    op.drop_index('ix_escalation_rules_active', table_name='escalation_rules')
    op.create_index(op.f('ix_escalation_rules_trigger_type'), 'escalation_rules', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_escalation_rules_is_active'), 'escalation_rules', ['is_active'], unique=False)
    op.alter_column('escalation_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('escalation_rules', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               comment='Lower = higher priority',
               existing_nullable=False)
    op.alter_column('escalation_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('escalation_rules', 'auto_escalate_further',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('escalation_rules', 'timeout_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Hours before auto-escalation')
    op.alter_column('escalation_rules', 'escalate_to_role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'CONTRIBUTOR', 'OBSERVER', name='escalate_role'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('escalation_rules', 'trigger_type',
               existing_type=sa.Enum('TIE_VOTE', 'QUORUM_FAILED', 'CSI_BELOW_THRESHOLD', 'CONFLICT_THRESHOLD', 'CONSTITUTIONAL_CONFLICT', 'MANUAL', 'TIMEOUT', name='escalation_trigger'),
               type_=sa.VARCHAR(length=50),
               comment='tie_vote | quorum_failure | csi_threshold | constitutional_conflict | timeout',
               existing_nullable=False)
    op.alter_column('escalation_rules', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('escalation_rules', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
