"""create conversation storage schema

Revision ID: 0f3513bed9f3
Revises: 
Create Date: 2025-11-17 22:46:27.646839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3513bed9f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgcrypto extension is available for gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Rickiest Rick, Supportive Rick, etc.'),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False, comment='0.40, 0.20, 0.10, 0.30 (must sum to 1.00)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='Future: multi-user support'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='openrouter, together_ai, etc.'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='free_tier | paid'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Lower = higher priority'),
    sa.Column('quota_limit', sa.BigInteger(), nullable=True, comment='Tokens per month (if known)'),
    sa.Column('tokens_used', sa.BigInteger(), nullable=False),
    sa.Column('last_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_env', sa.String(length=100), nullable=True, comment='ENV variable name'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='user | assistant | system'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_persona', sa.String(length=100), nullable=True, comment='Which Rick responded (if applicable)'),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Individual messages within conversations with LLM metadata'
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('llm_usage_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Detailed LLM API call tracking for cost analysis'
    )
    op.create_index(op.f('ix_llm_usage_log_created_at'), 'llm_usage_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_log_message_id'), 'llm_usage_log', ['message_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_log_provider_id'), 'llm_usage_log', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_log_provider_id'), table_name='llm_usage_log')
    op.drop_index(op.f('ix_llm_usage_log_message_id'), table_name='llm_usage_log')
    op.drop_index(op.f('ix_llm_usage_log_created_at'), table_name='llm_usage_log')
    op.drop_table('llm_usage_log')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('llm_providers')
    op.drop_table('conversations')
    op.drop_table('agent_personas')
    # ### end Alembic commands ###
