"""rename_vote_reason_to_justification

Revision ID: 50db557a3e7b
Revises: 9d7012fc92f5
Create Date: 2025-12-08 19:55:17.710644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50db557a3e7b'
down_revision: Union[str, Sequence[str], None] = '9d7012fc92f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('justification', sa.Text(), nullable=True))
    op.drop_column('votes', 'reason')
    # Copy data if needed? No, reason was just added and unused.
    # If we wanted to preserve data:
    # op.execute("UPDATE votes SET justification = reason")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('votes', 'justification')
