"""Add Phase 9 epistemic tables

Revision ID: 569456b4b01a
Revises: 87f5ff6dd55e
Create Date: 2025-12-08 17:01:32.637804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '569456b4b01a'
down_revision: Union[str, Sequence[str], None] = '87f5ff6dd55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False, comment='The hypothesis text'),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False, comment='Initial confidence (0-1)'),
    sa.Column('trigger_type', sa.String(length=50), nullable=False, comment='contradiction | sparse_region | uncertainty'),
    sa.Column('supporting_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of entity UUIDs supporting this hypothesis'),
    sa.Column('contradicting_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of entity UUIDs contradicting this hypothesis'),
    sa.Column('validation_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of validation steps: [search:X, papers:Y, ask_user]'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | validating | validated | rejected | escalated'),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_index(op.f('ix_hypotheses_trigger_type'), 'hypotheses', ['trigger_type'], unique=False)
    op.create_table('model_performance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hallucination_count', sa.Integer(), nullable=False),
    sa.Column('conflict_generation_rate', sa.Numeric(precision=4, scale=3), nullable=False, comment='Rate of conflicts generated by this model'),
    sa.Column('token_efficiency', sa.Numeric(precision=4, scale=3), nullable=False, comment='useful_tokens / total_tokens'),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performance_domain'), 'model_performance', ['domain'], unique=False)
    op.create_index(op.f('ix_model_performance_model_name'), 'model_performance', ['model_name'], unique=False)
    op.create_table('belief_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False, comment='The belief content'),
    sa.Column('claim_type', sa.String(length=50), nullable=False, comment='property | relationship | classification'),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False, comment='Confidence in this belief (0-1)'),
    sa.Column('source_doc_id', sa.UUID(), nullable=True, comment='Document establishing this belief'),
    sa.Column('superseded_by', sa.UUID(), nullable=True, comment='Link to newer belief that supersedes this'),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by'], ['belief_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_belief_snapshots_claim_type'), 'belief_snapshots', ['claim_type'], unique=False)
    op.create_index(op.f('ix_belief_snapshots_created_at'), 'belief_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_belief_snapshots_entity_id'), 'belief_snapshots', ['entity_id'], unique=False)
    op.create_index(op.f('ix_belief_snapshots_is_current'), 'belief_snapshots', ['is_current'], unique=False)
    op.create_table('epistemic_conflicts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='Primary entity with conflicting beliefs'),
    sa.Column('fact_1', sa.Text(), nullable=False, comment='First belief/claim'),
    sa.Column('fact_2', sa.Text(), nullable=False, comment='Contradicting belief/claim'),
    sa.Column('source_1_id', sa.UUID(), nullable=True, comment='Document source for fact_1'),
    sa.Column('source_2_id', sa.UUID(), nullable=True, comment='Document source for fact_2'),
    sa.Column('contradiction_type', sa.String(length=50), nullable=False, comment='temporal | source | domain | confidence'),
    sa.Column('confidence_delta', sa.Numeric(precision=4, scale=3), nullable=False, comment='Difference in confidence between beliefs'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='low | medium | high | critical'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | resolved | deprecated'),
    sa.Column('resolution', sa.String(length=50), nullable=True, comment='human_override | auto_reconciled | fact_1_wins | fact_2_wins'),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_1_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_2_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epistemic_conflicts_contradiction_type'), 'epistemic_conflicts', ['contradiction_type'], unique=False)
    op.create_index(op.f('ix_epistemic_conflicts_entity_id'), 'epistemic_conflicts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_epistemic_conflicts_status'), 'epistemic_conflicts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epistemic_conflicts_status'), table_name='epistemic_conflicts')
    op.drop_index(op.f('ix_epistemic_conflicts_entity_id'), table_name='epistemic_conflicts')
    op.drop_index(op.f('ix_epistemic_conflicts_contradiction_type'), table_name='epistemic_conflicts')
    op.drop_table('epistemic_conflicts')
    op.drop_index(op.f('ix_belief_snapshots_is_current'), table_name='belief_snapshots')
    op.drop_index(op.f('ix_belief_snapshots_entity_id'), table_name='belief_snapshots')
    op.drop_index(op.f('ix_belief_snapshots_created_at'), table_name='belief_snapshots')
    op.drop_index(op.f('ix_belief_snapshots_claim_type'), table_name='belief_snapshots')
    op.drop_table('belief_snapshots')
    op.drop_index(op.f('ix_model_performance_model_name'), table_name='model_performance')
    op.drop_index(op.f('ix_model_performance_domain'), table_name='model_performance')
    op.drop_table('model_performance')
    op.drop_index(op.f('ix_hypotheses_trigger_type'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_table('hypotheses')
    # ### end Alembic commands ###
