"""add_proposals_and_votes

Revision ID: 9d7012fc92f5
Revises: d4e5f6g7h8i9
Create Date: 2025-12-08 19:07:11.739725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d7012fc92f5'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6g7h8i9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('proposer_id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.Enum('DECISION', 'CONFIG_CHANGE', 'CONSTITUTIONAL_AMENDMENT', name='proposal_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'PASSED', 'REJECTED', 'EXPIRED', name='proposal_status'), nullable=False),
    sa.Column('quorum_required', sa.Float(), nullable=False),
    sa.Column('approval_threshold', sa.Float(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('total_for', sa.Float(), nullable=False),
    sa.Column('total_against', sa.Float(), nullable=False),
    sa.Column('total_abstain', sa.Float(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('result_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposer_id'], ['governance_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_proposer', 'proposals', ['proposer_id'], unique=False)
    op.create_index('ix_proposals_status', 'proposals', ['status'], unique=False)
    op.create_index('ix_proposals_type', 'proposals', ['proposal_type'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('choice', sa.Enum('FOR', 'AGAINST', 'ABSTAIN', name='vote_choice'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('delegated_from_id', sa.UUID(), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delegated_from_id'], ['governance_users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['governance_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'user_id', name='uq_vote_proposal_user')
    )
    op.create_index('ix_votes_proposal', 'votes', ['proposal_id'], unique=False)
    op.create_index('ix_votes_user', 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_user', table_name='votes')
    op.drop_index('ix_votes_proposal', table_name='votes')
    op.drop_table('votes')
    op.drop_index('ix_proposals_type', table_name='proposals')
    op.drop_index('ix_proposals_status', table_name='proposals')
    op.drop_index('ix_proposals_proposer', table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
