"""Knowledge Tier System for Epistemic Sovereignty (Story 11-5, Lock 7).

This module implements the immutable knowledge tier lattice that prevents
epistemic contamination by distinguishing grounded knowledge from narrative information.

The tier system enforces:
- K0 ≺ K1 ≺ K2 ≺ K3 ≺ K4 (partial order)
- Immutability (tiers cannot be downgraded without audit)
- Deterministic assignment (pure function of source metadata)
- Constitutional promotion rules

References:
- [Story 11-5: Knowledge Sovereignty]
- [Lock 7: Epistemic Sovereignty - "The system cannot lie to itself"]
"""

from __future__ import annotations

from enum import Enum
from typing import Optional
from dataclasses import dataclass


class KnowledgeTier(str, Enum):
    """Immutable knowledge tier classification.

    Tiers form a strict partial order where K0 is ground truth and K4 is noise.
    Once assigned, tiers can only be changed through constitutional promotion/demotion.

    Tier Hierarchy:
        K0 ≺ K1 ≺ K2 ≺ K3 ≺ K4

    Where ≺ means "more trusted than".
    """
    K0 = "ground_truth"           # Direct system telemetry, sensors
    K1 = "verified_derivation"    # Internal analytics, models
    K2 = "trust_scored_external"  # Peer-review, standards, books
    K3 = "narrative"              # News, blogs, commentary
    K4 = "noise"                  # Social media, forums, scrapes

    def __lt__(self, other: KnowledgeTier) -> bool:
        """Compare tiers for ordering (lower tier number = higher trust)."""
        order = {
            KnowledgeTier.K0: 0,
            KnowledgeTier.K1: 1,
            KnowledgeTier.K2: 2,
            KnowledgeTier.K3: 3,
            KnowledgeTier.K4: 4,
        }
        return order[self] < order[other]

    @property
    def trust_rank(self) -> int:
        """Numeric rank for trust ordering (0=highest, 4=lowest)."""
        return {
            KnowledgeTier.K0: 0,
            KnowledgeTier.K1: 1,
            KnowledgeTier.K2: 2,
            KnowledgeTier.K3: 3,
            KnowledgeTier.K4: 4,
        }[self]


class SourceType(str, Enum):
    """Source types for tier assignment.

    These are the canonical source classifications that determine
    the initial knowledge tier via the tier assignment function.
    """
    # K0: Ground Truth
    TELEMETRY = "telemetry"
    SENSOR = "sensor"
    ON_DEVICE_METRICS = "on_device_metrics"
    SYSTEM_LOGS = "system_logs"

    # K1: Verified Derivation
    INTERNAL_ANALYTICS = "internal_analytics"
    DERIVED_MODEL = "derived_model"
    PROCESSED_METRICS = "processed_metrics"

    # K2: Trust-Scored External
    PEER_REVIEWED_PAPER = "peer_reviewed_paper"
    ACADEMIC_BOOK = "academic_book"
    TECHNICAL_STANDARD = "technical_standard"
    OFFICIAL_DOCUMENTATION = "official_documentation"

    # K3: Narrative
    NEWS_ARTICLE = "news_article"
    BLOG_POST = "blog_post"
    EXPERT_COMMENTARY = "expert_commentary"
    INTERVIEW = "interview"

    # K4: Noise
    SOCIAL_MEDIA = "social_media"
    FORUM_POST = "forum_post"
    WEB_SCRAPE = "web_scrape"
    UNVERIFIED_SOURCE = "unverified_source"

    # Special
    AGENT_GENERATED = "agent_generated"
    SIMULATION = "simulation"


class CollectionMethod(str, Enum):
    """How the knowledge was collected.

    Collection method can influence tier assignment in edge cases
    and provides audit trail context.
    """
    DIRECT_CAPTURE = "direct_capture"      # Direct telemetry/sensor
    API_FETCH = "api_fetch"                # Structured API call
    DOCUMENT_PARSE = "document_parse"      # Parsed from trusted doc
    WEB_FETCH = "web_fetch"                # HTTP fetch
    USER_UPLOAD = "user_upload"            # Human-provided file
    AGENT_SYNTHESIS = "agent_synthesis"    # Generated by LLM
    SIMULATION_OUTPUT = "simulation_output" # Simulation result


@dataclass(frozen=True)
class TierAssignmentContext:
    """Context for tier assignment decision.

    This immutable context captures all information needed to
    deterministically assign a knowledge tier.
    """
    source_type: SourceType
    collection_method: CollectionMethod
    origin: str  # DOI, URL, file path, sensor ID, etc.
    initial_confidence: float = 1.0

    def __post_init__(self):
        """Validate constraints."""
        if not 0.0 <= self.initial_confidence <= 1.0:
            raise ValueError(f"initial_confidence must be in [0, 1], got {self.initial_confidence}")


def assign_tier(context: TierAssignmentContext) -> KnowledgeTier:
    """Pure, deterministic tier assignment function.

    This is the canonical tier assignment function Tier(i) that maps
    knowledge units to their immutable tier based on provenance.

    Formal Definition:
        Tier: (SourceType × CollectionMethod × Origin) → {K0, K1, K2, K3, K4}

    Invariant:
        ∀ contexts c1, c2: c1 = c2 ⇒ Tier(c1) = Tier(c2)
        (Same context always produces same tier)

    Args:
        context: Tier assignment context with source metadata

    Returns:
        Immutable KnowledgeTier for this knowledge unit

    References:
        [Story 11-5, AC #1: Knowledge Tier Lattice]
        [Tier Assignment Function specification]
    """
    source = context.source_type
    method = context.collection_method

    # K0: Ground Truth - Direct system telemetry
    if source in {
        SourceType.TELEMETRY,
        SourceType.SENSOR,
        SourceType.ON_DEVICE_METRICS,
        SourceType.SYSTEM_LOGS,
    }:
        return KnowledgeTier.K0

    # K1: Verified Derivation - Internal models and analytics
    if source in {
        SourceType.INTERNAL_ANALYTICS,
        SourceType.DERIVED_MODEL,
        SourceType.PROCESSED_METRICS,
    }:
        return KnowledgeTier.K1

    # K2: Trust-Scored External - Peer-reviewed, standards, books
    if source in {
        SourceType.PEER_REVIEWED_PAPER,
        SourceType.ACADEMIC_BOOK,
        SourceType.TECHNICAL_STANDARD,
        SourceType.OFFICIAL_DOCUMENTATION,
    }:
        return KnowledgeTier.K2

    # K3: Narrative - News, blogs, expert commentary
    if source in {
        SourceType.NEWS_ARTICLE,
        SourceType.BLOG_POST,
        SourceType.EXPERT_COMMENTARY,
        SourceType.INTERVIEW,
    }:
        return KnowledgeTier.K3

    # K4: Noise - Social media, forums, unverified
    if source in {
        SourceType.SOCIAL_MEDIA,
        SourceType.FORUM_POST,
        SourceType.WEB_SCRAPE,
        SourceType.UNVERIFIED_SOURCE,
    }:
        return KnowledgeTier.K4

    # Special Cases: Synthetic/Agent-Generated
    # These must be handled separately by Story 11-7 (Synthetic Certification)
    if source in {SourceType.AGENT_GENERATED, SourceType.SIMULATION}:
        # Synthetic content starts at K4 and can NEVER be promoted to K0-K2
        # without explicit human/governance certification (Story 11-7)
        return KnowledgeTier.K4

    # Default to K4 (noise) for unknown source types
    return KnowledgeTier.K4


def can_promote(from_tier: KnowledgeTier, to_tier: KnowledgeTier) -> bool:
    """Check if tier promotion is valid.

    Promotions can only move DOWN the tier chain (K4 → K3 → K2 → K1).
    K0 can never be assigned via promotion, only via initial assignment.

    Formal Rule:
        Promotion(i, t_new) = valid ⟺ Tier(i) > t_new ∧ t_new ≠ K0

    Args:
        from_tier: Current tier
        to_tier: Proposed new tier

    Returns:
        True if promotion is valid, False otherwise
    """
    # Can't promote to same tier
    if from_tier == to_tier:
        return False

    # Can't promote to K0 (only direct assignment)
    if to_tier == KnowledgeTier.K0:
        return False

    # Can only promote to lower-numbered (higher-trust) tier
    return to_tier.trust_rank < from_tier.trust_rank


def can_demote(from_tier: KnowledgeTier, to_tier: KnowledgeTier) -> bool:
    """Check if tier demotion is valid.

    Demotions can move UP the tier chain (K0 → K1 → K2 → K3 → K4).
    All demotions require audit logging.

    Args:
        from_tier: Current tier
        to_tier: Proposed new tier

    Returns:
        True if demotion is valid, False otherwise
    """
    # Can't demote to same tier
    if from_tier == to_tier:
        return False

    # Can only demote to higher-numbered (lower-trust) tier
    return to_tier.trust_rank > from_tier.trust_rank


class TierTransitionError(Exception):
    """Raised when an invalid tier transition is attempted."""

    def __init__(self, from_tier: KnowledgeTier, to_tier: KnowledgeTier, reason: str):
        self.from_tier = from_tier
        self.to_tier = to_tier
        self.reason = reason
        super().__init__(
            f"Invalid tier transition {from_tier.value} → {to_tier.value}: {reason}"
        )


def validate_tier_transition(
    from_tier: KnowledgeTier,
    to_tier: KnowledgeTier,
    reason: str,
    authorized: bool = False
) -> None:
    """Validate and enforce tier transition rules.

    This enforces the immutability constraint from AC #1:
    "Tiers cannot be downgraded without audit"

    Args:
        from_tier: Current tier
        to_tier: Proposed new tier
        reason: Human-readable reason for transition
        authorized: Whether this transition is authorized by governance

    Raises:
        TierTransitionError: If transition is invalid
    """
    # No-op if same tier
    if from_tier == to_tier:
        return

    # Check promotion validity
    if to_tier.trust_rank < from_tier.trust_rank:
        if not can_promote(from_tier, to_tier):
            raise TierTransitionError(
                from_tier, to_tier,
                "Invalid promotion: Cannot promote to K0, or tier ordering violation"
            )

    # Check demotion validity
    elif to_tier.trust_rank > from_tier.trust_rank:
        if not can_demote(from_tier, to_tier):
            raise TierTransitionError(
                from_tier, to_tier,
                "Invalid demotion: Tier ordering violation"
            )

        # Demotions require authorization
        if not authorized:
            raise TierTransitionError(
                from_tier, to_tier,
                "Demotion requires governance authorization"
            )
