"""Memory compilation service for JARVIS.

Aggregates conversations from PostgreSQL, uses LLM to generate insights,
and writes structured Markdown summaries for future retrieval.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import structlog
from sqlalchemy.orm import Session

from jarvis.database.models import Conversation, Message
from jarvis.database.postgres import get_session_factory
from jarvis.llm.client import LLMResponse, call_llm
from jarvis.memory.ingest import ingest_file

logger = structlog.get_logger(__name__)


@dataclass
class CompilationResult:
    """Result of memory compilation operation."""

    output_file: Path
    conversation_count: int
    message_count: int
    llm_response: LLMResponse
    ingestion_result: Optional[object] = None  # IngestionResult if auto-ingested


def _format_date_range(since: datetime, until: datetime) -> str:
    """Format date range as string."""
    return f"{since.strftime('%Y-%m-%d')} to {until.strftime('%Y-%m-%d')}"


def _aggregate_conversations(
    session: Session,
    since: datetime,
    until: datetime,
) -> tuple[list[Conversation], int]:
    """Query and aggregate conversations within date range.

    Returns:
        Tuple of (conversations list, total message count)
    """
    conversations = (
        session.query(Conversation)
        .filter(Conversation.created_at >= since, Conversation.created_at <= until)
        .all()
    )

    message_count = (
        session.query(Message)
        .join(Conversation)
        .filter(Conversation.created_at >= since, Conversation.created_at <= until)
        .count()
    )

    return conversations, message_count


def _build_compilation_prompt(conversations: list[Conversation]) -> str:
    """Build LLM prompt for insight generation from conversations.

    Aggregates all messages from conversations into a structured format for analysis.
    """
    if not conversations:
        return "No conversations to analyze."

    prompt_parts = [
        "Analyze the following conversations and generate a comprehensive insight summary.",
        "Focus on:",
        "- Key themes and topics discussed",
        "- Recurring patterns or questions",
        "- Important technical decisions or architectural choices",
        "- Action items or follow-ups mentioned",
        "- Notable learnings or discoveries",
        "",
        "Conversations:",
        "=" * 80,
        "",
    ]

    for conv in conversations:
        prompt_parts.append(f"Conversation {conv.id} (created: {conv.created_at}):")
        for msg in conv.messages:
            role_emoji = {"user": "👤", "assistant": "🤖", "system": "⚙️"}.get(
                msg.role, "❓"
            )
            prompt_parts.append(f"  {role_emoji} [{msg.role}]: {msg.content[:500]}")
            if len(msg.content) > 500:
                prompt_parts.append(f"    ... (truncated from {len(msg.content)} chars)")
        prompt_parts.append("")

    prompt_parts.extend(
        [
            "=" * 80,
            "",
            "Generate a structured Markdown summary with the following sections:",
            "## Key Themes",
            "## Emerging Patterns",
            "## Technical Decisions",
            "## Action Items",
            "## Notable Insights",
        ]
    )

    return "\n".join(prompt_parts)


def _format_markdown_output(
    date_range: str,
    conversation_count: int,
    message_count: int,
    llm_response: LLMResponse,
    generated_at: str,
) -> str:
    """Format compilation output as Markdown with front matter."""
    front_matter = f"""---
date_range: "{date_range}"
conversation_count: {conversation_count}
message_count: {message_count}
provider: "{llm_response.provider}"
model: "{llm_response.model}"
input_tokens: {llm_response.input_tokens}
output_tokens: {llm_response.output_tokens}
cost_usd: {llm_response.cost_usd:.4f}
generated_at: "{generated_at}"
domain: "jarvis-insights"
---

# Memory Insights: {date_range}

**Compiled from {conversation_count} conversations ({message_count} messages)**

{llm_response.content}

---

*Generated by JARVIS Memory Compilation*
*Provider: {llm_response.provider} | Model: {llm_response.model}*
*Cost: ${llm_response.cost_usd:.4f} | Tokens: {llm_response.input_tokens + llm_response.output_tokens}*
"""
    return front_matter


def _create_empty_result(output_file: Path, since: datetime, until: datetime) -> CompilationResult:
    """Create empty compilation result when no conversations found."""
    empty_response = LLMResponse(
        content="No conversations found in this time range.",
        provider="none",
        model="none",
        input_tokens=0,
        output_tokens=0,
        cost_usd=0.0,
    )
    
    empty_content = _format_markdown_output(
        _format_date_range(since, until),
        0,
        0,
        empty_response,
        datetime.now(timezone.utc).isoformat(),
    )
    
    output_file.write_text(empty_content, encoding="utf-8")
    
    return CompilationResult(
        output_file=output_file,
        conversation_count=0,
        message_count=0,
        llm_response=empty_response,
    )


def _handle_auto_ingestion(output_file: Path) -> Optional[object]:
    """Ingest compiled insights into memory if auto-ingest enabled.
    
    Returns:
        IngestionResult if successful, None otherwise
    """
    try:
        ingestion_result = ingest_file(
            path=output_file,
            domain="jarvis-insights",
        )
        logger.info(
            "compilation_auto_ingest_completed",
            chunks=ingestion_result.chunks,
            points=ingestion_result.points_written,
        )
        return ingestion_result
    except Exception as exc:
        logger.error(
            "compilation_auto_ingest_failed",
            error=str(exc),
            output_file=str(output_file),
        )
        return None


def compile_memories(
    since: datetime,
    until: Optional[datetime] = None,
    output_dir: Optional[Path] = None,
    auto_ingest: bool = True,
) -> CompilationResult:
    """Compile memories from conversations into LLM-generated insights.

    Args:
        since: Start date for conversation query (inclusive)
        until: End date for conversation query (inclusive, defaults to now)
        output_dir: Override default insights directory
        auto_ingest: If True, automatically ingest compiled insights into memory

    Returns:
        CompilationResult with file path, counts, LLM response, and optional ingestion result
    """
    if until is None:
        until = datetime.now(timezone.utc)

    # Ensure datetime objects are timezone-aware (UTC)
    if since.tzinfo is None:
        since = since.replace(tzinfo=timezone.utc)
    if until.tzinfo is None:
        until = until.replace(tzinfo=timezone.utc)

    # Default output directory: ~/.jarvis/knowledge/insights/
    if output_dir is None:
        output_dir = Path.home() / ".jarvis" / "knowledge" / "insights"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate output filename with date
    filename = f"{since.strftime('%Y-%m-%d')}_to_{until.strftime('%Y-%m-%d')}-insights.md"
    output_file = output_dir / filename

    logger.info(
        "compilation_start",
        since=since.isoformat(),
        until=until.isoformat(),
        output_file=str(output_file),
    )

    # Query conversations from PostgreSQL
    SessionFactory = get_session_factory()
    session = SessionFactory()
    try:
        conversations, message_count = _aggregate_conversations(session, since, until)

        if not conversations:
            logger.warning(
                "compilation_no_conversations",
                since=since.isoformat(),
                until=until.isoformat(),
            )
            return _create_empty_result(output_file, since, until)

        # Build LLM prompt from conversations
        prompt = _build_compilation_prompt(conversations)

        # Call LLM to generate insights
        system_message = (
            "You are JARVIS, an AI advisor analyzing conversation history to extract insights. "
            "Generate a structured, concise summary focusing on themes, patterns, and actionable intelligence."
        )
        llm_response = call_llm(prompt=prompt, system=system_message, max_tokens=4000)

        # Format as Markdown with front matter
        markdown_content = _format_markdown_output(
            _format_date_range(since, until),
            len(conversations),
            message_count,
            llm_response,
            datetime.now(timezone.utc).isoformat(),
        )

        # Write to file
        output_file.write_text(markdown_content, encoding="utf-8")

        logger.info(
            "compilation_completed",
            conversation_count=len(conversations),
            message_count=message_count,
            cost_usd=llm_response.cost_usd,
            output_file=str(output_file),
        )

        # Auto-ingest if requested
        ingestion_result = _handle_auto_ingestion(output_file) if auto_ingest else None

        return CompilationResult(
            output_file=output_file,
            conversation_count=len(conversations),
            message_count=message_count,
            llm_response=llm_response,
            ingestion_result=ingestion_result,
        )

    finally:
        session.close()
